"""add_gender_field_to_characters

Revision ID: 1570f549c52f
Revises: add_answer_text_field
Create Date: 2025-08-13 13:01:49.208511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1570f549c52f'
down_revision: Union[str, None] = 'add_answer_text_field'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='genderenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'gender')
    # ### end Alembic commands ###
