"""add_source_column_to_checklist_questions

Revision ID: 7b07d6908d09
Revises: 50b61de1fbfd
Create Date: 2025-08-06 21:11:58.436770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b07d6908d09'
down_revision: Union[str, None] = '50b61de1fbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_questions', sa.Column('source', sa.JSON(), nullable=True))
    op.drop_column('checklists', 'how_to_use')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('how_to_use', sa.TEXT(), nullable=True))
    op.drop_column('checklist_questions', 'source')
    # ### end Alembic commands ###
