"""redesign_checklist_structure_for_new_json

Revision ID: 8c15e2a3b4f6
Revises: 7b07d6908d09
Create Date: 2025-08-12 17:28:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c15e2a3b4f6'
down_revision: Union[str, None] = '7b07d6908d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new checklist_answers table
    op.create_table('checklist_answers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=False),
        sa.Column('value_male', sa.String(length=500), nullable=False),
        sa.Column('value_female', sa.String(length=500), nullable=False),
        sa.Column('exported_value_male', sa.Text(), nullable=True),
        sa.Column('exported_value_female', sa.Text(), nullable=True),
        sa.Column('hint', sa.Text(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['checklist_questions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add external_id to checklists
    with op.batch_alter_table('checklists') as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=False, server_default='temp'))
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_checklists_external_id', ['external_id'])
    
    # Add external_id to checklist_sections
    with op.batch_alter_table('checklist_sections') as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=False, server_default='temp'))
    
    # Add external_id to checklist_subsections
    with op.batch_alter_table('checklist_subsections') as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=False, server_default='temp'))
    
    # Add external_id to checklist_question_groups
    with op.batch_alter_table('checklist_question_groups') as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=False, server_default='temp'))
    
    # Update checklist_questions table
    with op.batch_alter_table('checklist_questions') as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=False, server_default='temp'))
        batch_op.add_column(sa.Column('answer_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=True))
        # Remove old columns from checklist_questions
        batch_op.drop_column('options')
        batch_op.drop_column('option_type')
        batch_op.drop_column('hint')
        batch_op.drop_column('source')
    
    # Update checklist_responses table
    with op.batch_alter_table('checklist_responses') as batch_op:
        batch_op.add_column(sa.Column('answer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_checklist_responses_answer', 'checklist_answers', ['answer_id'], ['id'])
        # Remove old answer column from checklist_responses
        batch_op.drop_column('answer')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore old checklist_responses structure
    with op.batch_alter_table('checklist_responses') as batch_op:
        batch_op.add_column(sa.Column('answer', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_checklist_responses_answer', type_='foreignkey')
        batch_op.drop_column('answer_id')
    
    # Restore old checklist_questions structure
    with op.batch_alter_table('checklist_questions') as batch_op:
        batch_op.add_column(sa.Column('source', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('hint', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('option_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=True))
        batch_op.drop_column('source_type')
        batch_op.drop_column('answer_type')
        batch_op.drop_column('external_id')
    
    # Remove external_id from other tables
    with op.batch_alter_table('checklist_question_groups') as batch_op:
        batch_op.drop_column('external_id')
    
    with op.batch_alter_table('checklist_subsections') as batch_op:
        batch_op.drop_column('external_id')
    
    with op.batch_alter_table('checklist_sections') as batch_op:
        batch_op.drop_column('external_id')
    
    # Remove new columns from checklists
    with op.batch_alter_table('checklists') as batch_op:
        batch_op.drop_constraint('uq_checklists_external_id', type_='unique')
        batch_op.drop_column('version')
        batch_op.drop_column('file_hash')
        batch_op.drop_column('external_id')
    
    # Drop checklist_answers table
    op.drop_table('checklist_answers')
    
    # ### end Alembic commands ###