"""add_sort_order_to_characters

Revision ID: 9ed551379708
Revises: 0cc3a9a04343
Create Date: 2025-08-16 19:16:10.967591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed551379708'
down_revision: Union[str, None] = '0cc3a9a04343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'sort_order')
    # ### end Alembic commands ###
