"""Create all tables including checklists

Revision ID: 9f7ffa4a5c45
Revises: c3566cd75d13
Create Date: 2025-08-05 15:24:51.363678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7ffa4a5c45'
down_revision: Union[str, None] = 'c3566cd75d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_table('checklist_sections',
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_sections_id'), 'checklist_sections', ['id'], unique=False)
    op.create_table('checklist_subsections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['checklist_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_subsections_id'), 'checklist_subsections', ['id'], unique=False)
    op.create_table('checklist_question_groups',
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subsection_id'], ['checklist_subsections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_question_groups_id'), 'checklist_question_groups', ['id'], unique=False)
    op.create_table('checklist_questions',
    sa.Column('question_group_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_group_id'], ['checklist_question_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_questions_id'), 'checklist_questions', ['id'], unique=False)
    op.create_table('checklist_responses',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('FOUND_IN_TEXT', 'LOGICALLY_DERIVED', 'IMAGINED', name='sourcetype'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['checklist_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_responses_id'), 'checklist_responses', ['id'], unique=False)
    op.create_table('checklist_response_history',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('previous_answer', sa.Text(), nullable=True),
    sa.Column('previous_source_type', sa.Enum('FOUND_IN_TEXT', 'LOGICALLY_DERIVED', 'IMAGINED', name='sourcetype'), nullable=True),
    sa.Column('previous_comment', sa.Text(), nullable=True),
    sa.Column('previous_version', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['checklist_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_response_history_id'), 'checklist_response_history', ['id'], unique=False)
    op.drop_index('ix_character_checklist_responses_id', table_name='character_checklist_responses')
    op.drop_table('character_checklist_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_checklist_responses',
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('checklist_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=True),
    sa.Column('confidence_level', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_character_checklist_responses_id', 'character_checklist_responses', ['id'], unique=False)
    op.drop_index(op.f('ix_checklist_response_history_id'), table_name='checklist_response_history')
    op.drop_table('checklist_response_history')
    op.drop_index(op.f('ix_checklist_responses_id'), table_name='checklist_responses')
    op.drop_table('checklist_responses')
    op.drop_index(op.f('ix_checklist_questions_id'), table_name='checklist_questions')
    op.drop_table('checklist_questions')
    op.drop_index(op.f('ix_checklist_question_groups_id'), table_name='checklist_question_groups')
    op.drop_table('checklist_question_groups')
    op.drop_index(op.f('ix_checklist_subsections_id'), table_name='checklist_subsections')
    op.drop_table('checklist_subsections')
    op.drop_index(op.f('ix_checklist_sections_id'), table_name='checklist_sections')
    op.drop_table('checklist_sections')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.drop_table('checklists')
    # ### end Alembic commands ###
